//! Spectral kurtosis — "is this bin noise, or is something in it?"
//!
//! Every other detector here asks whether a bin is *loud*. This one asks whether
//! it is **Gaussian**, which is a different and often better question. Thermal
//! noise, room tone, the hiss of a ventilation loop — all of it is the sum of
//! many independent contributions, so by the central limit theorem the real and
//! imaginary parts of each STFT bin are Gaussian and its power is exponentially
//! distributed. That distribution has a known shape, and *anything generated by
//! a process* departs from it, however quiet it is.
//!
//! The estimator is Nita & Gary's, the one radio astronomy uses to excise
//! interference:
//!
//! ```text
//!         M + 1   /     S2        \
//!   SK =  ----- * | M * ---  -  1 |         S1 = sum |X|^2,  S2 = sum |X|^4
//!         M - 1   \     S1^2      /
//! ```
//!
//! and it is calibrated by construction:
//!
//! | what is in the bin | SK |
//! |---|---|
//! | Gaussian noise | **1** |
//! | a steady sinusoid | **0** — a constant amplitude has less scatter than noise |
//! | anything intermittent — a stroke sweeping through, a keyed tone, a click | **> 1** |
//!
//! Reported here in **sigmas from the Gaussian expectation** rather than raw, so
//! that the number means the same thing whatever the window length: the variance
//! of the estimator under noise is `4/M`, so a departure is
//! `(SK - 1) * sqrt(M) / 2`. Zero is "indistinguishable from noise", and that is
//! the only value a threshold ever needs to be compared against.
//!
//! What it is *for* here is the same thing it is for in astronomy: refusing to
//! spend effort on bins that carry no information. A drawn stroke sweeping
//! through a bin occupies it briefly and leaves — which is exactly the
//! intermittency this measures — while the ambience it is buried in is
//! stationary by definition.

/// Frames the estimate is formed over.
///
/// At the pipeline's 23.4 frames per second this is about 2.7 seconds, which is
/// the scale a drawn stroke crosses a single frequency bin on. Longer windows
/// estimate the noise better but dilute a brief event into it; the estimator's
/// own noise falls only as `1/sqrt(M)`, so there is little to win by extending
/// it and a real signal to lose.
pub const WINDOW_FRAMES: usize = 64;

/// Per-bin spectral kurtosis over a sliding window.
#[derive(Debug, Clone)]
pub struct SpectralKurtosis {
    /// `bins` power values per frame, oldest overwritten.
    ring: Vec<f32>,
    write: usize,
    filled: usize,
    window: usize,
    /// Running sums of power and of power squared, per bin.
    ///
    /// `f64` is not fussiness: `S2` accumulates the *fourth* power of a
    /// magnitude, and in `f32` a bin at a plausible level overflows the
    /// mantissa long before the window fills.
    s1: Vec<f64>,
    s2: Vec<f64>,
    /// Frames since the sums were last rebuilt from the ring.
    ///
    /// Carrying a sum by adding the new sample and subtracting the old one is
    /// exact in arithmetic and badly wrong in floating point, once the signal
    /// changes scale. A bin that held stroke energy at 1e-6 and now holds
    /// silence at 1e-30 has a *true* sum around 1e-30 and an accumulated
    /// rounding error around 1e-22, so the sum is pure error — and `S2/S1^2`
    /// then returns whatever that error happens to be. Measured on the Landscape
    /// Signal, this produced a peak of 1.6e24 sigma, for a statistic that cannot
    /// mathematically exceed `M - 1`.
    ///
    /// Rebuilding once per window costs one extra pass every `window` frames,
    /// which is nothing amortized, and makes the error bounded by a single
    /// window's worth of addition rather than by the whole run's.
    since_refresh: usize,
    /// Departure from the Gaussian expectation, in sigmas.
    sigma: Vec<f32>,
}

impl SpectralKurtosis {
    pub fn new(bins: usize, window: usize) -> Self {
        let window = window.max(4);
        Self {
            ring: vec![0.0; bins * window],
            write: 0,
            filled: 0,
            window,
            s1: vec![0.0; bins],
            s2: vec![0.0; bins],
            since_refresh: 0,
            sigma: vec![0.0; bins],
        }
    }

    pub fn bins(&self) -> usize {
        self.sigma.len()
    }

    /// True once the window is full and the estimate means anything.
    pub fn ready(&self) -> bool {
        self.filled == self.window
    }

    /// Departure from Gaussian noise per bin, in sigmas. All zero until
    /// [`SpectralKurtosis::ready`].
    pub fn sigma(&self) -> &[f32] {
        &self.sigma
    }

    pub fn reset(&mut self) {
        self.ring.fill(0.0);
        self.s1.fill(0.0);
        self.s2.fill(0.0);
        self.sigma.fill(0.0);
        self.write = 0;
        self.filled = 0;
        self.since_refresh = 0;
    }

    /// Add one frame of per-bin power.
    pub fn update(&mut self, powers: &[f32]) {
        let bins = self.sigma.len();
        debug_assert_eq!(powers.len(), bins);
        let evicting = self.filled == self.window;
        let slot = self.write * bins;

        for (i, &power) in powers.iter().enumerate().take(bins) {
            let p = if power.is_finite() && power > 0.0 {
                power as f64
            } else {
                0.0
            };

            if evicting {
                let old = self.ring[slot + i] as f64;
                self.s1[i] -= old;
                self.s2[i] -= old * old;
            }
            self.ring[slot + i] = p as f32;
            self.s1[i] += p;
            self.s2[i] += p * p;
        }

        self.write = (self.write + 1) % self.window;
        self.filled = (self.filled + 1).min(self.window);

        if self.filled < self.window {
            return;
        }

        self.since_refresh += 1;
        if self.since_refresh >= self.window {
            self.since_refresh = 0;
            self.s1.fill(0.0);
            self.s2.fill(0.0);
            for frame in 0..self.window {
                let base = frame * bins;
                for i in 0..bins {
                    let p = self.ring[base + i] as f64;
                    self.s1[i] += p;
                    self.s2[i] += p * p;
                }
            }
        }

        let m = self.window as f64;
        // Under Gaussian noise the estimator has variance 4/M, so this converts
        // a raw SK into "how surprising is this".
        let inv_sigma = (m / 4.0).sqrt();
        for i in 0..bins {
            let s1 = self.s1[i];
            // A bin that is identically zero — a band the source never fills —
            // carries no evidence either way, and dividing by its S1 would
            // manufacture some.
            if s1 <= 0.0 {
                self.sigma[i] = 0.0;
                continue;
            }
            // Rounding can leave the sums a hair negative after eviction.
            let s2 = self.s2[i].max(0.0);
            let sk = ((m + 1.0) / (m - 1.0)) * (m * s2 / (s1 * s1) - 1.0);
            let value = ((sk - 1.0) * inv_sigma) as f32;
            // `S2 <= S1^2` with equality when one frame carries everything, so
            // SK cannot exceed M - 1 and the departure cannot exceed this. A
            // value beyond it is arithmetic, not evidence.
            let bound = ((m - 2.0) * inv_sigma) as f32;
            self.sigma[i] = if value.is_finite() {
                value.clamp(-bound, bound)
            } else {
                0.0
            };
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Exponentially distributed power, which is what a Gaussian bin produces.
    struct Rng(u32);

    impl Rng {
        fn next_unit(&mut self) -> f64 {
            self.0 = self.0.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            // Never exactly zero, so the logarithm below stays finite.
            ((self.0 >> 8) as f64 + 0.5) / 16_777_216.0
        }

        fn next_exponential(&mut self, mean: f64) -> f32 {
            (-mean * self.next_unit().ln()) as f32
        }
    }

    fn settle(sk: &mut SpectralKurtosis, frames: usize, mut f: impl FnMut(usize) -> f32) {
        for frame in 0..frames {
            let v = f(frame);
            sk.update(&[v]);
        }
    }

    #[test]
    fn gaussian_noise_sits_at_zero_sigma() {
        let mut sk = SpectralKurtosis::new(1, 256);
        let mut rng = Rng(0x1234_5678);
        settle(&mut sk, 4096, |_| rng.next_exponential(1e-6));
        let s = sk.sigma()[0];
        assert!(
            s.abs() < 3.0,
            "noise must not look like a signal, reads {s:.2} sigma"
        );
    }

    /// The calibration only means anything if it holds at any level, since a
    /// faint signal is the entire point.
    #[test]
    fn the_verdict_does_not_depend_on_loudness() {
        for mean in [1e-12, 1e-6, 1.0, 1e6] {
            let mut sk = SpectralKurtosis::new(1, 256);
            let mut rng = Rng(0xABCD_1234);
            settle(&mut sk, 4096, |_| rng.next_exponential(mean));
            let s = sk.sigma()[0];
            assert!(
                s.abs() < 3.0,
                "noise at mean {mean:e} reads {s:.2} sigma; the statistic must be scale-free"
            );
        }
    }

    #[test]
    fn a_steady_tone_reads_strongly_negative() {
        // Constant power: less scatter than noise has, which is what SK below
        // one means. This is the case that separates a held tone from hiss.
        let mut sk = SpectralKurtosis::new(1, 64);
        settle(&mut sk, 256, |_| 1e-4);
        let s = sk.sigma()[0];
        assert!(
            s < -3.0,
            "a constant amplitude must read below noise, reads {s:.2} sigma"
        );
    }

    #[test]
    fn an_intermittent_signal_reads_strongly_positive() {
        // A stroke sweeping through a bin: loud for a quarter of the window,
        // absent otherwise. This is what the gate is meant to keep.
        let mut sk = SpectralKurtosis::new(1, 64);
        let mut rng = Rng(0x5555_1111);
        settle(&mut sk, 512, |frame| {
            let noise = rng.next_exponential(1e-8);
            if frame % 64 < 16 { noise + 1e-5 } else { noise }
        });
        let s = sk.sigma()[0];
        assert!(
            s > 5.0,
            "an intermittent signal must stand out, reads {s:.2} sigma"
        );
    }

    /// Where the statistic actually starts to see something, measured rather
    /// than assumed — and in which direction it moves, which is not obvious.
    ///
    /// A signal *added* to noise reduces the bin's relative scatter, pulling SK
    /// toward the tone-like side; a signal that dominates the frames it occupies
    /// increases the scatter across the window and pushes it the other way. The
    /// two effects cancel somewhere in between, so a weak intermittent signal is
    /// the hardest case for this statistic and there is no point pretending
    /// otherwise.
    #[test]
    fn the_detection_floor_is_where_it_was_measured() {
        let noise_mean = 1e-6f64;
        println!("\n  signal/noise   sigma");
        let mut measured = Vec::new();
        for ratio in [0.0, 0.1, 0.3, 1.0, 3.0, 10.0, 100.0] {
            let mut sk = SpectralKurtosis::new(1, 64);
            let mut rng = Rng(0x9999_2222);
            settle(&mut sk, 1024, |frame| {
                let noise = rng.next_exponential(noise_mean);
                // Present a quarter of the time, as a stroke crossing a bin is.
                if frame % 64 < 16 {
                    noise + (noise_mean * ratio) as f32
                } else {
                    noise
                }
            });
            let s = sk.sigma()[0];
            println!("  {ratio:>10.1}   {s:>6.2}");
            measured.push((ratio, s));
        }
        println!();

        for (ratio, s) in &measured {
            if *ratio <= 0.3 {
                assert!(
                    s.abs() < 3.0,
                    "at {ratio}x the noise there is nothing to see, yet it reads {s:.2}"
                );
            }
            if *ratio >= 10.0 {
                assert!(
                    *s > 3.0,
                    "at {ratio}x the noise it must be obvious, reads {s:.2}"
                );
            }
        }
    }

    #[test]
    fn nothing_is_reported_before_the_window_fills() {
        let mut sk = SpectralKurtosis::new(3, 32);
        for _ in 0..31 {
            sk.update(&[1.0, 2.0, 3.0]);
            assert!(!sk.ready());
            assert_eq!(sk.sigma(), &[0.0, 0.0, 0.0]);
        }
        sk.update(&[1.0, 2.0, 3.0]);
        assert!(sk.ready());
    }

    #[test]
    fn degenerate_input_is_finite() {
        let mut sk = SpectralKurtosis::new(4, 8);
        for _ in 0..32 {
            sk.update(&[0.0, f32::NAN, f32::INFINITY, -1.0]);
        }
        assert!(sk.sigma().iter().all(|s| s.is_finite()), "{:?}", sk.sigma());
        // An empty bin carries no evidence, so it must read exactly zero rather
        // than some artefact of dividing by nothing.
        assert_eq!(sk.sigma()[0], 0.0);
    }

    /// The bug this was shipped with for ten minutes: a bin whose level changes
    /// by twenty orders of magnitude, repeatedly, which is what a stroke
    /// sweeping through silence looks like.
    #[test]
    fn a_bin_that_changes_scale_stays_within_the_theoretical_bound() {
        let mut sk = SpectralKurtosis::new(1, 64);
        // SK is bounded by M - 1, so the departure is bounded by (M - 2)/2*sqrt(M).
        let bound = (64.0f32 - 2.0) * (64.0f32 / 4.0).sqrt();
        let mut worst = 0.0f32;
        for block in 0..200 {
            let level = if block % 2 == 0 { 1e-6 } else { 1e-30 };
            for _ in 0..37 {
                sk.update(&[level]);
                let s = sk.sigma()[0];
                assert!(s.is_finite(), "went non-finite at block {block}");
                worst = worst.max(s.abs());
            }
        }
        assert!(
            worst <= bound,
            "reads {worst:.3e} sigma against a mathematical ceiling of {bound:.1}"
        );
    }

    #[test]
    fn reset_clears_the_estimate() {
        let mut sk = SpectralKurtosis::new(1, 8);
        settle(&mut sk, 64, |_| 1e-4);
        assert!(sk.ready());
        sk.reset();
        assert!(!sk.ready());
        assert_eq!(sk.sigma(), &[0.0]);
    }

    /// The sliding window must forget: a bin that was a tone and is now noise
    /// has to stop reading as a tone.
    #[test]
    fn the_window_forgets_what_left_it() {
        let mut sk = SpectralKurtosis::new(1, 64);
        settle(&mut sk, 128, |_| 1e-4);
        assert!(sk.sigma()[0] < -3.0);

        let mut rng = Rng(0x7777_3333);
        settle(&mut sk, 512, |_| rng.next_exponential(1e-6));
        let s = sk.sigma()[0];
        assert!(
            s.abs() < 3.0,
            "once the tone has left the window the bin is noise again, reads {s:.2}"
        );
    }
}
